
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGIN CLOSEDATA CLOSEHEADER CLOSEHREF CLOSEROW CONTENT GARBAGE OPENDATA OPENHEADER OPENHREF OPENROW OPENTABLE PATTERN THEADCLOSE THEADOPEN \n    start : BEGIN THEADOPEN skiptag THEADCLOSE OPENTABLE getdata\n    \n    skiptag : GARBAGE skiptag \n            | PATTERN skiptag\n            | CONTENT skiptag\n            | OPENROW skiptag\n            | CLOSEROW skiptag\n            | OPENDATA skiptag\n            | CLOSEDATA skiptag\n            | OPENHEADER skiptag\n            | CLOSEHEADER skiptag\n            |\n    \n    getdata : OPENROW handledata CLOSEROW getdata\n            | \n    \n    handledata : onlydata handledata\n               | \n    \n    comment : GARBAGE\n            | \n    \n    onlydata : OPENDATA CLOSEDATA comment \n             | OPENDATA GARBAGE CONTENT GARBAGE CLOSEDATA comment\n             | OPENDATA OPENHREF CONTENT CLOSEHREF CLOSEDATA comment\n             | OPENDATA OPENHREF CONTENT PATTERN CONTENT CLOSEHREF CLOSEDATA comment\n             | OPENDATA GARBAGE GARBAGE CLOSEDATA comment\n             | OPENDATA CONTENT CLOSEDATA comment \n    '
    
_lr_action_items = {'BEGIN':([0,],[2,]),'$end':([1,24,25,30,36,],[0,-13,-1,-13,-12,]),'THEADOPEN':([2,],[3,]),'GARBAGE':([3,5,6,7,8,9,10,11,12,13,29,32,33,40,41,43,49,50,55,],[5,5,5,5,5,5,5,5,5,5,33,38,39,44,38,38,38,38,38,]),'PATTERN':([3,5,6,7,8,9,10,11,12,13,42,],[6,6,6,6,6,6,6,6,6,6,47,]),'CONTENT':([3,5,6,7,8,9,10,11,12,13,29,33,35,47,],[7,7,7,7,7,7,7,7,7,7,34,40,42,51,]),'OPENROW':([3,5,6,7,8,9,10,11,12,13,24,30,],[8,8,8,8,8,8,8,8,8,8,26,26,]),'CLOSEROW':([3,5,6,7,8,9,10,11,12,13,26,27,28,31,32,37,38,41,43,45,48,49,50,52,53,55,56,],[9,9,9,9,9,9,9,9,9,9,-15,30,-15,-14,-17,-18,-16,-17,-17,-23,-22,-17,-17,-19,-20,-17,-21,]),'OPENDATA':([3,5,6,7,8,9,10,11,12,13,26,28,32,37,38,41,43,45,48,49,50,52,53,55,56,],[10,10,10,10,10,10,10,10,10,10,29,29,-17,-18,-16,-17,-17,-23,-22,-17,-17,-19,-20,-17,-21,]),'CLOSEDATA':([3,5,6,7,8,9,10,11,12,13,29,34,39,44,46,54,],[11,11,11,11,11,11,11,11,11,11,32,41,43,49,50,55,]),'OPENHEADER':([3,5,6,7,8,9,10,11,12,13,],[12,12,12,12,12,12,12,12,12,12,]),'CLOSEHEADER':([3,5,6,7,8,9,10,11,12,13,],[13,13,13,13,13,13,13,13,13,13,]),'THEADCLOSE':([3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,],[-11,14,-11,-11,-11,-11,-11,-11,-11,-11,-11,-2,-3,-4,-5,-6,-7,-8,-9,-10,]),'OPENTABLE':([14,],[24,]),'OPENHREF':([29,],[35,]),'CLOSEHREF':([42,51,],[46,54,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'skiptag':([3,5,6,7,8,9,10,11,12,13,],[4,15,16,17,18,19,20,21,22,23,]),'getdata':([24,30,],[25,36,]),'handledata':([26,28,],[27,31,]),'onlydata':([26,28,],[28,28,]),'comment':([32,41,43,49,50,55,],[37,45,48,52,53,56,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> BEGIN THEADOPEN skiptag THEADCLOSE OPENTABLE getdata','start',6,'p_start','t1.py',79),
  ('skiptag -> GARBAGE skiptag','skiptag',2,'p_skiptag','t1.py',84),
  ('skiptag -> PATTERN skiptag','skiptag',2,'p_skiptag','t1.py',85),
  ('skiptag -> CONTENT skiptag','skiptag',2,'p_skiptag','t1.py',86),
  ('skiptag -> OPENROW skiptag','skiptag',2,'p_skiptag','t1.py',87),
  ('skiptag -> CLOSEROW skiptag','skiptag',2,'p_skiptag','t1.py',88),
  ('skiptag -> OPENDATA skiptag','skiptag',2,'p_skiptag','t1.py',89),
  ('skiptag -> CLOSEDATA skiptag','skiptag',2,'p_skiptag','t1.py',90),
  ('skiptag -> OPENHEADER skiptag','skiptag',2,'p_skiptag','t1.py',91),
  ('skiptag -> CLOSEHEADER skiptag','skiptag',2,'p_skiptag','t1.py',92),
  ('skiptag -> <empty>','skiptag',0,'p_skiptag','t1.py',93),
  ('getdata -> OPENROW handledata CLOSEROW getdata','getdata',4,'p_getdata','t1.py',97),
  ('getdata -> <empty>','getdata',0,'p_getdata','t1.py',98),
  ('handledata -> onlydata handledata','handledata',2,'p_handledata','t1.py',103),
  ('handledata -> <empty>','handledata',0,'p_handledata','t1.py',104),
  ('comment -> GARBAGE','comment',1,'p_comment','t1.py',108),
  ('comment -> <empty>','comment',0,'p_comment','t1.py',109),
  ('onlydata -> OPENDATA CLOSEDATA comment','onlydata',3,'p_onlydata','t1.py',113),
  ('onlydata -> OPENDATA GARBAGE CONTENT GARBAGE CLOSEDATA comment','onlydata',6,'p_onlydata','t1.py',114),
  ('onlydata -> OPENDATA OPENHREF CONTENT CLOSEHREF CLOSEDATA comment','onlydata',6,'p_onlydata','t1.py',115),
  ('onlydata -> OPENDATA OPENHREF CONTENT PATTERN CONTENT CLOSEHREF CLOSEDATA comment','onlydata',8,'p_onlydata','t1.py',116),
  ('onlydata -> OPENDATA GARBAGE GARBAGE CLOSEDATA comment','onlydata',5,'p_onlydata','t1.py',117),
  ('onlydata -> OPENDATA CONTENT CLOSEDATA comment','onlydata',4,'p_onlydata','t1.py',118),
]
